version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5455:5432"
    volumes:
      - ~/apps/ecommerce_app/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce
